#!/bin/bash

gnuplot << EOF

set terminal pdf

set xlabel 't'
set ylabel 'Ni'
set title "N=20"
set output 'N_20.pdf'
plot "/tmp/spread_pgrk_20" using 1:2 w lp pt 10 ps 1 lc 2 title "pgrk", "/tmp/spread_spgrk_20" using 1:2 w lp pt 19 ps 1 lc 10 title "spgrk"
set output

set title "N=50"
set output 'N_50.pdf'
plot "/tmp/spread_pgrk_50" using 1:2 w lp pt 10 ps 1 lc 2 title "pgrk", "/tmp/spread_spgrk_50" using 1:2 w lp pt 19 ps 1 lc 10 title "spgrk"
set output

set title "N=100"
set output 'N_100.pdf'
plot "/tmp/spread_pgrk_100" using 1:2 w lp pt 10 ps 1 lc 2 title "pgrk", "/tmp/spread_spgrk_100" using 1:2 w lp pt 19 ps 1 lc 10 title "spgrk"
set output

EOF
