#!/bin/bash
# this script is used to submit tasks to the cluster's queue. 
# the file should include all the paper wants.

#######################################################check usage.
if [ "$#" -ne "2" ]; then
	echo "wrong param number, usage: \"$0 theta exec_file_name\" or \"$0 lambda exec_file_name\""
	exit -1
elif [ "$1" != "theta" ] && [ "$1" != "lambda" ]; then
	echo "wrong param name, usage: \"$0 theta exec_file_name\" or \"$0 lambda exec_file_name\""
	exit -1
elif [ ! -f "$2" ]; then
	echo "\"$2\" don't exist";
	exit -1
fi
exec_name=$2

########################################################clear cluster environment.
qdel -u xiaor
currentTask=$(qstat -cb | grep xiaor | wc -l)
while [ $currentTask -ne 0 ]
do
	echo "current running task Num: $currentTask"
	echo "wait 2s.."
	sleep 2s
	currentTask=$(qstat -cb | grep xiaor | wc -l)
done

cluster_output_dir=./cluster_output/
if [ -d $cluster_output_dir ]; then
	rm -r $cluster_output_dir
	mkdir $cluster_output_dir
else
	mkdir $cluster_output_dir
fi

###################################################default value
limitN=5
theta=1.0
lambda=0

#####################################################choice
param_name=$1
param_scope=
if [ $param_name = "theta" ]; then
	for param in {1..31}
	do
		tmp=$(awk "BEGIN{print $param / 20 + 0.45 }")
		param_scope="$param_scope $tmp"
	done
elif [ $param_name = "lambda" ]; then
	for param in {1..21}
	do
		tmp=$(awk "BEGIN{print $param / 20 - 0.05 }")
		param_scope="$param_scope $tmp"
	done
fi

#####################################################clean environment
script_dir="${param_name}_scrpit"
if [ -d $script_dir ]; then
	rm -r $script_dir
	mkdir $script_dir
else
	mkdir $script_dir
fi

result_dir="${param_name}_result"
if [ -d $result_dir ]; then
	rm -r $result_dir
	mkdir $result_dir
else
	mkdir $result_dir
fi

for d12 in 1 2
do 
	if [ $d12  = 1 ]; then
		L1=500
		L2=1000
		L3=2000
	else
		L1=2500
		L2=10000
		L3=40000
	fi
	for L in $L1 $L2 $L3
	do
		for param in $param_scope
		do
			for seed in {1..20}
			do
				currentTask=$(qstat -cb | grep xiaor | wc -l)
				echo "current running task Num: $currentTask"
				while [ $currentTask -ge 30 ]
				do
					echo "wait 20s.."
					sleep 20s
					currentTask=$(qstat -cb | grep xiaor | wc -l)
					echo "current running task Num: $currentTask"
				done

				script_result_filename="${param_name}_${d12}_${L}_${param}_$seed"
				exec_script=$script_dir/$script_result_filename
				result_file=$result_dir/$script_result_filename
				if [ $param_name = "theta" ]; then
					echo "$exec_name $d12 $L $seed $limitN $param $lambda |tee  $result_file" > $exec_script
				elif [ $param_name = "lambda" ]; then
					echo "$exec_name $d12 $L $seed $limitN $theta $param |tee  $result_file" > $exec_script
				else
					echo "wrong param_name: $param_name"
					exit -1
				fi
				qsub -cwd -o $cluster_output_dir -e $cluster_output_dir $exec_script 
				sleep 1s
			done
		done
	done
done
